pub mod contact;
pub mod features;
pub mod footer;
pub mod header;
pub mod hero;
pub mod testimonials;
pub mod core_capabilities;
pub mod about_founder;
pub mod recent_projects;

pub use contact::*;
pub use features::*;
pub use footer::*;
pub use header::*;
pub use hero::*;
pub use testimonials::*;
pub use core_capabilities::*;
pub use about_founder::*;
pub use recent_projects::*;